FROM golang:alpine AS builder

RUN apk add --no-cache git

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GRPC_PORT=

RUN mkdir /common
COPY common/ /common

WORKDIR /employee_service

COPY go.mod .
COPY go.sum .
RUN go mod download

#copy my code from where I am right now
#to working dir specified in workdir command
COPY . .  

#run go build. write output in bin
#run all packages (specified by .) 
RUN go build -o bin .

#now dir structure inside docker image becomes /employee_service/bin (binary is in bin)


FROM golang:alpine

RUN apk add --no-cache git

RUN apk upgrade --update \
    && apk add bash git gcc g++ libc-dev


WORKDIR /app/

EXPOSE 8002

COPY --from=builder /builder/bin /app/bin
