version: '3'
services:
  employee-service:
    build:
      context: ../employee_service
      dockerfile: dockerfile
    environment:
      - GRPC_PORT=:9002
    ports:
      - "9002:9002"
 
  user-service:
    build:
      context: ../user_service
      dockerfile: dockerfile
    environment:
      - GRPC_PORT=:9001
    ports:
      - "9001:9001"
  
  mobile-core-service:
    build:
      context: ../mobile_core_service
      dockerfile: dockerfile
    environment:
      - APP_PORT=8000
      - USER_GRPC_PORT=user-service:9001
      - EMPLOYEE_GRPC_PORT=employee-service:9002
    ports:
      - "8000:8000"
    depends_on: 
      - employee-service
      - user-service
  
