FROM golang:alpine

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GRPC_PORT=9001


WORKDIR /user_service

COPY go.mod .
COPY go.sum .
RUN go mod download

#copy my code from where I am right now
#to working dir specified in workdir command
COPY . .  

#run go build. write output in main
#run all packages (specified by .) 
RUN go build -o bin .

#now dir structure inside docker image becomes /user_service/bin (binary is in bin)


EXPOSE 9001

CMD ["/user_service/bin"]