FROM golang:1.16-alpine AS builder

RUN apk add --no-cache git

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GRPC_PORT=9001 \
    GITHUB_PAT=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

RUN git config --global url."https://${GITHUB_PAT}:x-oauth-basic@github.com/Fatema-Moaiyadi".insteadOf "https://github.com/Fatema-Moaiyadi"

WORKDIR /user_service

COPY go.mod .
COPY go.sum .
RUN go mod download

#copy my code from where I am right now
#to working dir specified in workdir command
COPY . .  

#run go build. write output in main
#run all packages (specified by .) 
RUN go build -o bin .

#now dir structure inside docker image becomes /user_service/bin (binary is in bin)


FROM alpine:latest

RUN apk add --no-cache git

RUN apk upgrade --update \
    && apk add bash git gcc g++ libc-dev


WORKDIR /app

COPY --from=builder /user_service/bin /app/bin
RUN touch /app/application.yaml