FROM golang:1.16-alpine

RUN apk add --no-cache git

RUN apk upgrade --update \
    && apk add bash git gcc g++ libc-dev


ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    APP_PORT= \
    USER_GRPC_PORT= \
    EMPLOYEE_GRPC_PORT=

WORKDIR /app

COPY . . 

WORKDIR /app

RUN go mod download

RUN go build -o mobile_core_service

EXPOSE 8000

CMD ["/app/mobile_core_service"]